# Generated by Django 5.2.5 on 2025-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertask',
            options={'verbose_name': 'UserTask', 'verbose_name_plural': 'UserTasks'},
        ),
        migrations.AlterField(
            model_name='usertask',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low Priority'), ('high', 'High Priority'), ('medium', 'Medium Priority')], null=True),
        ),
        migrations.AlterModelTable(
            name='usertask',
            table='userstask',
        ),
    ]
